name: Docker

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: build and push docker image
      run: |
        echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build -t oc-imagebuilder .
        docker tag oc-imagebuilder:latest ghcr.io/${{ github.repository }}/oc-imagebuilder:latest
        docker push ghcr.io/${{ github.repository }}/oc-imagebuilder:latest
